### ISSUE TITLE
Object reference not set to an instance error running code

### ISSUE THREAD

**Issue by TheDragonGypsy** [ciskosv/BanTwithLurkerBots#2]
I get the following error in my logs when the script runs:

[2024-02-27 13:27:01.730 ERR] InlineCode :: There was an error running the instance for 'Ban lurker bots'
System.NullReferenceException: Object reference not set to an instance of an object.
   at p2ea767c88d3446abd68321c2e7ec5a0.CPHInline.Execute()
   at _Y4JKKJ4AUzN1QJ4uPxxThVFoFkU._1E6TCq4GT4JTKamHBgwTw57HHst(Dictionary`2 , Boolean , String )
   at _Y4JKKJ4AUzN1QJ4uPxxThVFoFkU._1E6TCq4GT4JTKamHBgwTw57HHst(Dictionary`2 , Boolean , String )
   at _FhvHS3w1VXB1Ho2Y8xgHA0T0RHH._6BBcHOZ36eR8qbT4jrN6Nr5EELT(Guid , _U0cznaZcmBzxFD3OY9gzqw5E1Wp , Dictionary`2 , Boolean , String , Boolean )
   at _1W5RNnfa0iViHIMtXQregjkmLmz._YkddRmQ3fyKrWAcPTTA0hxalzui.MoveNext()

It sends the start message to chat then does nothing.

**Comment by ciskosv** [comment]
Hello @TheDragonGypsy could you please confirm you have followed the instructions for this update:
https://www.youtube.com/watch?v=-iPTIaJCDDA&t=609s&ab_channel=CiskoGaming

**Comment by TheDragonGypsy** [comment]
Took me a bit to find where the trigger was in 2.2, but that fixed it.  Thanks!

**Comment by ciskosv** [comment]
Awesome @TheDragonGypsy !!!
